# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - snailboard-backend(Production), Build and deploy Spring app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        
    - name: set gradle
      run: gradle wrapper 

    - name: Build with Gradle
      run: . ./gradlew bootJar

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: snailboard-backend
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D554D81CC0BE45F5A8AED96F4B78745A }}
        package: ${{ github.workspace }}/build/libs/*.jar

